sidebar:
  logo:
    avatar: '[config.avatar](/about/)' # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
    title: '[config.title](/)' # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  menu:
    post: '[btn.blog](/)'
    wiki: '[btn.wiki](/projects/)'
    friends: #'[友链](/friends/)'
    about: '[关于](/about/)'

article:
  auto_cover: false
  auto_excerpt: 0

open_graph:
  enable: true

footer:
  social:
    - title: GitHub
      icon: '<i class="ri-github-line ri-lg"></i>'
      url: https://github.com/jilstingray
    - title: Steam
      icon: '<i class="ri-steam-fill ri-lg"></i>'
      url: https://steamcommunity.com/id/stingray_117/
    - title: Keylol
      icon: '<i class="ri-discuss-line ri-lg"></i>'
      url: https://keylol.com/suid-1406507